name: release

on:
  push:
    tags:
      - "*"
jobs:
  # Generic uberjar. It is built without graalvm flags
  build_uberjar:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Build uberjar
        run: make uberjar

      - name: Creating release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/jarbloat.jar

  # graalvm windows build
  build_on_windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.5.0
      - uses: microsoft/setup-msbuild@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 11
          distribution: 'graalvm-community'
          components: ['native-image']
          version: 20.3.0

      - name: Install dependencies
        run: |
          choco install --verbose make
          choco install --verbose lein

      - name: Build native
        run: make native

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          version: latest
          file: target/jarbloat.exe
          args: '-7'

      - name: Renaming file
        run: ren jarbloat.exe jarbloat-windows-amd64.exe
        working-directory: target

      - name: Creating release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*.exe

  # graalvm mac build
  build_on_mac:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 11
          distribution: 'graalvm-community'
          components: ['native-image']
          version: 20.3.0

      - name: Install dependencies
        run: |
          brew install leiningen

      - name: Build native
        run: make native

      # UPX doesn't work on >= Ventura (https://github.com/upx/upx/issues/612)
      #- name: Run UPX
      #  uses: svenstaro/upx-action@v2
      #  with:
      #    file: target/jarbloat
      #    args: '-7'

      - name: Renaming file
        run: mv target/jarbloat target/jarbloat-darwin-amd64

      - name: Creating release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/jarbloat-darwin*

  # graalvm linux build
  build_on_linux:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 11
          distribution: 'graalvm-community'
          components: ['native-image']
          version: 20.3.0

      - name: Build native
        run: make native

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          version: latest
          file: target/jarbloat
          args: '-7'

      - name: Renaming file
        run: mv target/jarbloat target/jarbloat-linux-amd64

      - name: Creating release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/jarbloat-linux-amd64
