name: jarbloat tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: lein deps

    - name: Run code lint
      run: make lint

    - name: Run tests
      run: make test
